#!/usr/bin/env bash
set -euo pipefail

source "${BASH_SOURCE%/*}/../helper/common.sh"

function get_env_from_yaml
{
    local file="$1"
    local line=""
    local env_flag="false"
    cat "$file" | while read -r line; do
        line="$(echo "${line}" | sed 's/[[:space:]]*$//')"
        if [[ "$line" == "env:" ]]; then
            env_flag="true"
            continue
        fi

        if [[ "$env_flag" == "true" && "$line" =~ ^[A-Za-z].*:$ ]]; then
            break;
        fi
        line="$(echo "${line}" | sed "s/^[[:space:]]*\([^:]*\): \(.*\)/\1='\2'/")"
        echo "$line"
    done
}

function main
{
    if [[ "${BUILDKITE_PLUGIN_DYNAMIC_BRANCH_POST_COMMAND:-}" == "true" ]]; then
        exit 0
    fi

    local file_path="${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite/executed.steps.yaml"

    build_and_run_docker > "$file_path"

    set -a
    eval $(get_env_from_yaml "$file_path")
    set +a

    upload_pipeline "$file_path" && rm "$file_path"
}

main
