#!/usr/bin/env bash
set -euo pipefail

plugin_root="${BASH_SOURCE%/*}/.."
source "${plugin_root}/helper/common.sh"

function main
{
    if [[ "${BUILDKITE_PLUGIN_DYNAMIC_BRANCH_POST_COMMAND:-}" == "true" ]]; then
        exit 0
    fi

    run_plugin "$plugin_root"
}

main
