#!/usr/bin/env bash
set -euo pipefail

plugin_root="${BASH_SOURCE%/*}/.."
venv_dir="${BUILDKITE_BUILD_CHECKOUT_PATH}/../.dynamic-branch-plugin-venv"

# Try to use explicit python3 if its installed
python_bin="python3"
pip_bin="pip3"
if ! [[ -x "$(command -v ${python_bin})" ]]; then
    python_bin="python"
    pip_bin="pip"
fi

if [[ ! $(${python_bin} -m ${pip_bin} freeze) =~ "virtualenv==" ]]; then
    ${python_bin} -m ${pip_bin} install "virtualenv==16.7.7"
fi
${python_bin} -m virtualenv "${venv_dir}"

platform=$(${python_bin} -c "import platform; print(platform.system())")
if [[ "${platform}" == "Windows" ]]; then
    venv_bin="${venv_dir}/Scripts"
else
    venv_bin="${venv_dir}/bin"
fi

"${venv_bin}/python" -m pip install -r "${plugin_root}/python/requirements.txt"

eval "$("${venv_bin}/python" "${plugin_root}/python/main.py")"
