#!/usr/bin/env bash
set -euo pipefail

plugin_root="${BASH_SOURCE%/*}/.."
source "${plugin_root}/helper/common.sh"

function main
{
    if [[ "${BUILDKITE_PLUGIN_DYNAMIC_BRANCH_POST_COMMAND:-}" != "true" ]]; then
        exit 0
    fi

    set -a
    eval $(build_and_run_docker "${plugin_root}/Dockerfile" "${plugin_root}/.buildkite")
    set +a

    if [[ -f "$EXE_BRANCH" ]]; then
        upload_pipeline "$EXE_BRANCH" && rm "$EXE_BRANCH"
    fi
}

main
