#!/usr/bin/env bash
set -euo pipefail

plugin_root="${BASH_SOURCE%/*}/.."
source "${plugin_root}/helper/common.sh"

function main
{
    if [[ "${BUILDKITE_PLUGIN_DYNAMIC_BRANCH_POST_COMMAND:-}" != "true" ]]; then
        exit 0
    fi

    local file_path="${plugin_root}/executed.steps.yaml"

    build_and_run_docker "${BASH_SOURCE%/*}/../Dockerfile" > "$file_path"

    upload_pipeline "$file_path" && rm "$file_path"
}

main
